from typing import TypedDict, List, Dict, Any

class AgentLog(TypedDict):
    agent: str      # Name of the agent (e.g., "GIS Planner", "GIS Developer", "GIS QA")
    log_type: str   # Type of log (e.g., "thought", "output", "tool_call", "error")
    content: str    # The log content
    timestamp: str  # Time of the log

class AgentState(TypedDict):
    task: str               # The original user spatial problem/request
    plan: str               # The spatial methodology & steps generated by GIS Planner
    draft_code: str         # The Python GIS script generated by GIS Developer
    explanation: str        # Explanation/methodology summary from Developer
    qa_feedback: str        # Spatial and logical auditing comments from GIS QA
    qa_approved: bool       # Flag indicating if the solution meets QA standards
    iterations: int         # Current number of revision loops
    max_iterations: int     # Guardrail to prevent infinite loops
    logs: List[AgentLog]    # Timeline logs of agent activities for Streamlit dashboard visualization
