import datetime
import re
from core.state import AgentState, AgentLog
from core.llm import get_llm
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.runnables import RunnableConfig

QA_SYSTEM_PROMPT = """You are a Senior GIS Quality Assurance Engineer. 
Your role is to audit the Python code generated by the GIS Developer and ensure it adheres to professional GIS programming standards.

Audit Criteria:
1. Coordinate Reference System (CRS) Safety:
   - Check if distance, area, buffer, or spatial overlay operations are performed on a geographic CRS (like EPSG:4326) using degrees. This is a critical error! These operations MUST be performed in a projected metric CRS (e.g. UTM zones or EPSG:3857) and then reprojected back if needed.
   - Example error: `gdf.buffer(500)` where gdf is in EPSG:4326 (which adds a 500-degree buffer instead of 500 meters!).
2. Folium Visualizations:
   - Folium maps require coordinates in EPSG:4326 (WGS 84, Lat/Lon). Verify that any GeoDataFrames plotted on a Folium map are reprojected using `.to_crs(epsg=4326)` or `.to_crs(4326)`.
3. Spatial Code Quality:
   - Ensure `shapely.geometry` shapes (Point, Polygon, LineString) are imported and instantiated correctly.
   - Check for missing library imports (like `geopandas` as `gpd`, `folium`, etc.).
   - Verify that data paths are safe and there are no syntax errors.

Your response must start with one of the following lines:
APPROVED: YES - if the code meets all standards, is correct, and is ready for production.
APPROVED: NO - if there are any issues, bugs, or improvements needed.

Following that, provide a bulleted list of QA findings, including:
- A review of the CRS handling.
- Any bugs or improvements identified.
- Detailed recommendations if revisions are required.
"""

def qa_node(state: AgentState, config: RunnableConfig = None) -> dict:
    """
    GIS QA Inspector agent node. Audits the code and flags issues.
    """
    configurable = config.get("configurable", {}) if config else {}
    provider = configurable.get("provider", None)
    model_name = configurable.get("model_name", None)
    temperature = configurable.get("temperature", None)
    api_key = configurable.get("api_key", None)
    base_url = configurable.get("base_url", None)
    
    llm = get_llm(
        provider=provider,
        model_name=model_name,
        temperature=temperature,
        api_key=api_key,
        base_url=base_url
    )
    
    task = state["task"]
    draft_code = state.get("draft_code", "")
    
    # Prompt
    prompt_content = f"Task: {task}\n\nDraft Code to Audit:\n```python\n{draft_code}\n```"
    messages = [
        SystemMessage(content=QA_SYSTEM_PROMPT),
        HumanMessage(content=prompt_content)
    ]
    
    timestamp = datetime.datetime.now().strftime("%H:%M:%S")
    state_logs = state.get("logs", [])
    
    state_logs.append(AgentLog(
        agent="GIS QA Inspector",
        log_type="thought",
        content="Auditing CRS conversions, geometry operations, and code correctness...",
        timestamp=timestamp
    ))
    
    try:
        response = llm.invoke(messages)
        qa_output = response.content
        
        # Parse approval status
        is_approved = False
        match = re.match(r"^APPROVED:\s*(YES|NO)", qa_output, re.IGNORECASE)
        if match:
            approval_str = match.group(1).upper()
            is_approved = (approval_str == "YES")
            
        timestamp = datetime.datetime.now().strftime("%H:%M:%S")
        state_logs.append(AgentLog(
            agent="GIS QA Inspector",
            log_type="output",
            content=f"Audit complete. Approved: {'YES' if is_approved else 'NO'}\n\nFeedback:\n{qa_output}",
            timestamp=timestamp
        ))
        
        return {
            "qa_feedback": qa_output,
            "qa_approved": is_approved,
            "logs": state_logs
        }
    except Exception as e:
        timestamp = datetime.datetime.now().strftime("%H:%M:%S")
        state_logs.append(AgentLog(
            agent="GIS QA Inspector",
            log_type="error",
            content=f"Failed to audit code: {str(e)}",
            timestamp=timestamp
        ))
        return {
            "qa_approved": False,
            "qa_feedback": f"Error during QA auditing: {str(e)}",
            "logs": state_logs
        }
